#!/bin/bash
### Entfernt Sonderzeichen aus Datei- und Verzeichnisnamen 
### (KDE-Servicemenu)

NEWFILE=$(echo "${1}" | sed -f ~/.detoxrc )

if [ ! "${1}" == "${NEWFILE}" ]
  then
  mv "${1}" "${NEWFILE}" && echo "${1}    moved to    ${NEWFILE}" || echo "ERROR: ${1}    not moved"
  fi
  