#!/usr/bin/bash
#
# installiert die in diesem Verzeichnis vorhandenen Dateien
# fuer den lokalen Benutzer
#

######################### KDE 5 / Plasma / Dolphin
# Wenn entsprechendes Ziel-Verzeichnisse noch nicht existieren, dann lege es an
[ -d ~/.local/share/kservices5/ServiceMenus ] || mkdir -p ~/.local/share/kservices5/ServiceMenus 

# kopiere die Dateien in die entsprechenden Verzeichnisse
cp -t ~/.local/share/kservices5/ServiceMenus/ *.desktop

# in Dolphn als Service anmelden
kbuildsycoca4
kbuildsycoca5

######################### Cinnamon / Nemo
# Wenn entsprechende Ziel-Verzeichnisse noch nicht existieren, dann lege sie an
[ -d ~/.local/share/nemo/actions ] || mkdir -p ~/.local/share/nemo/actions 
[ -d ~/.local/share/nemo/scripts ] || mkdir -p ~/.local/share/nemo/scripts 

# kopiere die Dateien in die entsprechenden Verzeichnisse
cp -t ~/.local/share/nemo/actions/ *.nemo_action 
cp -t ~/.local/share/nemo/scripts/ nsc_*
# nemo neu starten
nemo -q
nemo

######################## Arbeitsscript in 
# Wenn entsprechendes Ziel-Verzeichnisse noch nicht existieren, dann lege es an
[ -d ~/bin ] || mkdir ~/bin

# kopiere die Dateien in dieses Verzeichnis
cp -t ~/bin/ ksm_pdf_tool nemowrapper_pdftool


# Datei ausfuehrbar machen
chmod u+x ~/bin/ksm_pdf_tool ~/bin/nemowrapper_pdftool

